import { Injectable } from "@angular/core";
import { Observable, Subject } from "rxjs";

@Injectable()
export class SearchServiceMock {
  private params = new Subject<Object>();
  paramsUpdated$ = this.params.asObservable();

  runSearch() {
    return Observable.of({"_embedded":{"results":[{"alternativeNames":["Office of the Solicitor"],"suggestion":"office of the solicitor","_rScore":94,"name":"OFFICE OF THE SOLICITOR","cgac":"016","_type":"federalOrganization","organizationHierarchy":[{"organizationId":100012049,"level":1,"name":"LABOR, DEPARTMENT OF"},{"organizationId":100116263,"level":2,"name":"OFFICE OF THE SOLICITOR"}],"description":null,"_id":"100116263","type":"AGENCY","shortName":"SOL","isActive":true},{"alternativeNames":null,"suggestion":"office of the commissioner","_rScore":94,"name":"OFFICE OF THE COMMISSIONER","cgac":null,"_type":"federalOrganization","organizationHierarchy":[{"organizationId":100012403,"level":1,"name":"SOCIAL SECURITY ADMINISTRATION"},{"organizationId":100532696,"level":2,"name":"OFFICE OF THE COMMISSIONER"}],"description":null,"_id":"100532696","type":"AGENCY","shortName":null,"isActive":true},{"alternativeNames":["Office of the Secretary"],"suggestion":"office of the secretary","_rScore":94,"name":"OFFICE OF THE SECRETARY","cgac":"013","_type":"federalOrganization","organizationHierarchy":[{"organizationId":100035122,"level":1,"name":"COMMERCE, DEPARTMENT OF"},{"organizationId":100109415,"level":2,"name":"OFFICE OF THE SECRETARY"}],"description":"The General Administration account within the Office of the Secretary provides funding for the Secretary, Deputy Secretary and support staff.  Responsibilities involve policy development and implementation affecting U.S. and international activities as well as establishing the internal goals and operations of the Department.  The functions include serving as the primary liaison with the Executive Branch, and Congressional and private sector groups, and acting as the management and administrative control point for the Department. ","_id":"100109415","type":"AGENCY","shortName":"","isActive":true},{"alternativeNames":null,"suggestion":"dept of the navy","_rScore":94,"name":"DEPT OF THE NAVY","cgac":null,"_type":"federalOrganization","organizationHierarchy":[{"organizationId":100525174,"level":1,"name":"DEPT OF DEFENSE"},{"organizationId":100525248,"level":2,"name":"DEPT OF THE NAVY"}],"description":null,"_id":"100525248","type":"AGENCY","shortName":null,"isActive":true},{"alternativeNames":null,"suggestion":"office of the secretary","_rScore":94,"name":"OFFICE OF THE SECRETARY","cgac":null,"_type":"federalOrganization","organizationHierarchy":[{"organizationId":100538443,"level":1,"name":"COMMERCE, DEPARTMENT OF"},{"organizationId":100538446,"level":2,"name":"OFFICE OF THE SECRETARY"}],"description":null,"_id":"100538446","type":"AGENCY","shortName":null,"isActive":true}]},"_links":{"self":{"href":"https://52samdotgovsearchcomp.apps.prod-iae.bsp.gsa.gov/sgs/v1/search?index=fh&index=fh&q=the&q=the&page=1&page=1&size=5&size=5"}},"page":{"size":5,"totalElements":431,"totalPages":87,"number":1,"maxAllowedRecords":10000}});
  }
}
